services:
  postgres:
    image: 'postgres:latest'
    container_name: wallet-wise-postgres
    environment:
      - 'POSTGRES_DB=wallet-wise'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: wallet-wise-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181


  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: wallet-wise-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
